### PR TITLE
Fixes Flutter color class interference

### PR DESCRIPTION
**Pull request by EliasDeuss**
I was getting interference with the packages classes and the built in flutter classes.

### CODE REVIEW

**Comment by LichKing-2234** [comment]
Thanks for your PR, but can use the `as` keyword to name library, such as:
```
import 'package:agora_rtc_engine/rtc_engine.dart' as AgoraRtcEngine;
...
AgoraRtcEngine.Color
...
```
So, it is necessary to rename the class?

**Comment by shinriyo** [comment]
@EliasDeuss can you fix it ?

**Comment by EliasDeuss** [comment]
> Thanks for your PR, but can use the `as` keyword to name library, such as:
> 
> ```
> 
> import 'package:agora_rtc_engine/rtc_engine.dart' as AgoraRtcEngine;
> 
> ...
> 
> AgoraRtcEngine.Color
> 
> ...
> 
> ```
> 
> So, it is necessary to rename the class?

@LichKing-2234 
Yes you can do that but it's generally a good idea not to name classes the same as a flutter UI class.

**Comment by EliasDeuss** [comment]
@shinriyo you can use my fork if you want in your pubspec.

**Comment by LichKing-2234** [comment]
> > Thanks for your PR, but can use the `as` keyword to name library, such as:
> > ```
> > 
> > import 'package:agora_rtc_engine/rtc_engine.dart' as AgoraRtcEngine;
> > 
> > ...
> > 
> > AgoraRtcEngine.Color
> > 
> > ...
> > ```
> > 
> > 
> > So, it is necessary to rename the class?
> 
> @LichKing-2234
> Yes you can do that but it's generally a good idea not to name classes the same as a flutter UI class.

I agree with you, so I remove the `Color` class, use the flutter `Color` class now.

https://github.com/AgoraIO/Agora-Flutter-SDK/commit/a09c1f17cc4dbbfbafedd496168ff8787f66275b

**Comment by LichKing-2234** [comment]
this pr will be close after https://github.com/AgoraIO/Agora-Flutter-SDK/commit/a09c1f17cc4dbbfbafedd496168ff8787f66275b been merged.

**Pull request closed without merging**
