### PR TITLE
Null Safety

### PR DESCRIPTION
**Pull request by fareesh**

### CODE REVIEW

**Comment by LichKing-2234** [comment]
Thanks for your PR, I have pushed the code to the branch `rc/3.3.+`, this PR will close after it be merged to the master branch.

**Comment by davidAg9** [comment]
publish the null safe version please

**Comment by LichKing-2234** [comment]
@davidAg9 It will be published today.

**Comment by LichKing-2234** [comment]
the version `4.0.0-rc.0` has been published to migrate null safety.

**Pull request closed without merging**
