### PR TITLE
A Simpler Example for pub.dev

### PR DESCRIPTION
**Pull request by tadaspetra**
When visiting [Example Tab on pub.dev](https://pub.dev/packages/agora_rtc_engine/example) the current example leads to a much bigger example inside the GitHub repo. Although it is a good way to showcase a lot of the features, the examples on pub.dev should be simple and easy to copy paste. 

For the current example the copy to clipboard option doesn't really make sense. Most of the file data is in the GitHub repo, so the copy to clipboard doesn't copy working code.
Screen Shot 2021-07-19 at 3 39 20 PM

Without these other files, and without the other context, there is no Agora code being showcased in this example. I believe this is an issue since there are a large portion of developers that might not go to the GitHub repo, and the current example shown on pub.dev doesn't showcase Agora.

### Proposition
- Keep the current example for people that start using it more, and dig deeper
- Add a new very simple and quick example for people that are getting a first impression of the package.

I believe this will bring in more users to try it out.

### CODE REVIEW

**Comment by LichKing-2234** [comment]
First, thanks for your PR. But some files contains format diff, could you pls revert it?

**Review by LichKing-2234 — CHANGES_REQUESTED** [review]
Revert format changes.

**Comment by tadaspetra** [comment]
@LichKing-2234 Which files contain format diff? 

If you referring to the import statements, those aren't formatting changes. The previous `main.dart` I moved inside the examples folder, so that there wasn't 2 `main.dart` files in the /lib directory. So the imports are updated with the new path

**Comment by LichKing-2234** [comment]
Oh! My mistake. I will review it again.

**Comment by digitallysavvy** [comment]
@LichKing-2234 why was this closed and not merged?

**Comment by LichKing-2234** [comment]
I will add a simple example because the git history has been changed.

**Comment by LichKing-2234** [comment]
Use `example.md` instead of.

Followed https://dart.cn/tools/pub/package-layout#examples.

**Comment by LichKing-2234** [comment]
@tadaspetra  @digitallysavvy 
https://pub.dev/packages/agora_rtc_engine/versions/4.0.7-rc.0/example

@tadaspetra Whatever, thanks for your PR!

**Pull request closed without merging**
